image_parameters:
  height_og: 800
  img_path: ../img/static_frame_from_video.png
  p1:
  - 15
  - 571
  p2:
  - 22
  - 12
  p3:
  - 773
  - 566
  p4:
  - 762
  - 20
  size_frame: '800'
  width_og: 600
